function quiz(){
    let answer= prompt("wHATS MY FAVORITE COLOR")
    if(answer==="BLUE"){
        document.querySelector(".result").innerText ="you rule"
    }else{document.querySelector(".result").innerText ="Game over, you lose"}
}

function quiz2(){
    let answer2= prompt("WHATS MY FAVORITE NUMBER ")
    if(answer2==="27"){
        document.querySelector(".result2").innerText ="you rule"
    }else{document.querySelector(".result2").innerText ="Game over, you lose"}
}



function quiz3(){
    let answer3= prompt("WHATS MY FAVORITE PET ")
    if(answer3==="CAT"){
        document.querySelector(".result3").innerText ="you rule"
    }else{document.querySelector(".result3").innerText ="Game over, you lose"}
}
function quiz4(){
    let answer4= prompt("WHATS MY FAVORITE FOOD ")
    if(answer4==="PIZZA"){
        document.querySelector(".result4").innerText ="you rule"
    }else{document.querySelector(".result4").innerText ="Game over, you lose"}
}

function quiz5(){
    let answer5= prompt("WHATS MY FAVORITE NAME  ")
    if(answer5==="HOSS"){
        document.querySelector(".result5").innerText ="you rule"
    }else{document.querySelector(".result5").innerText ="Game over, you lose"}
}








